# Assignment 2: Implementation of numPy

### *Name: Ishita Gupta*
### *Roll No: J018*

In [1]:
import numpy as np
import time

### Defining matrices

In [4]:
A = np.random.randn(3,3)
B = np.random.randn(3,3)
C = np.random.randn(3,3)
I = np.identity(3)

In [8]:
print("A:\n",A)
print("B:\n",A)
print("C:\n",A)
print("I:\n",I)

A:
 [[ 1.04408091  0.1496757  -0.25247508]
 [ 0.84703683  0.50577368  0.39264502]
 [ 0.14184493 -1.14321737  0.63979663]]
B:
 [[ 1.04408091  0.1496757  -0.25247508]
 [ 0.84703683  0.50577368  0.39264502]
 [ 0.14184493 -1.14321737  0.63979663]]
C:
 [[ 1.04408091  0.1496757  -0.25247508]
 [ 0.84703683  0.50577368  0.39264502]
 [ 0.14184493 -1.14321737  0.63979663]]
I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Proving properties of matrix multiplication

#### 1. Not Commutative (A.B != B.A)

In [15]:
AB = A.dot(B)
BA = B.dot(A)

print("A.B:\n", AB)
print("\n")
print("B.A:\n", BA)

A.B:
 [[-0.60275725 -0.15820504 -0.90527951]
 [ 0.44433724 -0.03313252 -0.60072812]
 [-1.12238553 -1.79043471  0.10847131]]


B.A:
 [[-1.12375392  0.58885892 -0.54340987]
 [ 2.35647728  0.84806681  0.09805179]
 [ 0.28184771 -0.48696227 -0.25173136]]


##### The matrices are not equal. Hence, proved.

#### 2. Associative ((A.B)C = (A)B.C)

In [22]:
ABc = np.dot(A,B).dot(C)
aBC = A.dot(np.dot(B,C))

print('(A.B)C\n', ABc)
print("\n")
print('(A)B.C\n', aBC)

(A.B)C
 [[ 0.65965469 -1.04957564 -0.38168464]
 [ 1.05764179 -1.0974695   0.10204877]
 [-0.15184529 -2.99219382 -0.43714125]]


(A)B.C
 [[ 0.65965469 -1.04957564 -0.38168464]
 [ 1.05764179 -1.0974695   0.10204877]
 [-0.15184529 -2.99219382 -0.43714125]]


##### The matrices are equal. Hence, proved.

#### 3. Distributive (A(B+C) = AB + AC)

In [19]:
p = np.dot(A, B + C)
q = np.dot(A,B) + np.dot(A,C)

print('A(B+C)\n', p)
print("\n")
print('AB + AC\n', q)

A(B+C)
 [[ 0.42852374 -0.83101335 -0.50263853]
 [ 0.40576657  0.97982402 -0.19323819]
 [-1.21752267 -3.56989118  0.27296332]]


AB + AC
 [[ 0.42852374 -0.83101335 -0.50263853]
 [ 0.40576657  0.97982402 -0.19323819]
 [-1.21752267 -3.56989118  0.27296332]]


##### The matrices are equal. Hence, proved.

#### 4. Identity Multiplication (AI = IA)

In [21]:
AI=np.dot(A,I)
IA=np.dot(I,A)

print('A.I\n', AI)
print("\n")
print('I.A\n', IA)

A.I
 [[ 1.04408091  0.1496757  -0.25247508]
 [ 0.84703683  0.50577368  0.39264502]
 [ 0.14184493 -1.14321737  0.63979663]]


I.A
 [[ 1.04408091  0.1496757  -0.25247508]
 [ 0.84703683  0.50577368  0.39264502]
 [ 0.14184493 -1.14321737  0.63979663]]


##### The matrices are equal. Hence, proved.

### Matrix Inverse

In [24]:
A_inv = np.linalg.inv(A) 

print("Inverse of A:\n", A_inv)

Inverse of A:
 [[ 0.77530792  0.19358024  0.18714949]
 [-0.48802238  0.70639662 -0.6260999 ]
 [-1.04390853  1.21930387  0.4027616 ]]


### numPy vs Looping  (Time Difference)

In [26]:
P = np.random.randn(10000,10000)
Q = np.random.randn(10000,10000)
p = [list(i)for i in P]
q = [list(i)for i in Q]

In [27]:
start_loop = time.time()
r = []

for i in range(10000):
    row=[]
    for j in range(10000):
        row.append(p[i][j]+q[i][j])
    r.append(row)
    
end_loop=time.time()

In [28]:
start_numpy = time.time()
R = P + Q
end_numpy = time.time()

In [29]:
print(f'Time taken by loops = {end_loop - start_loop} seconds') 
print(f'Time taken by numPy = {end_numpy - start_numpy} seconds')

Time taken by loops = 1504.634391784668 seconds
Time taken by numPy = 313.792498588562 seconds


##### This clearly shows that numPy is way faster than loops.